### PR TITLE
added Portuguese - Brazil

### PR DESCRIPTION
**Pull request by Gabrielforest**
I have used the same structure from `es`

### CODE REVIEW

**Comment by jakewilliami** [comment]
Hey @Gabrielforest, this looks great, thanks so much for contributing!  I changed the structure a bit to be more consistent with the other supported languages (namely to be more consistent with the interface for English).

I'd like to raise a couple of questions:
  1. Do you know if Portugal Portuguese is the same as Brazilian Portuguese in terms of counting?  I know that pronunciation is quite different, but I'm not so familiar so am unsure about counting.  If they are the same then we can rename `:pt_BR -> :pt`.
  2. Would you mind adding some more tests for Brazilian Portuguese?  I think we should test floats, if you have implemented them, and just add some more test cases.

Thank you again for your help.  Great work!

**Comment by jakewilliami** [comment]
@Gabrielforest, once again, great work!  I wonder if it's possible to merge [`pt.jl`](src/pt.jl) and [`pt_BR.jl`](src/pt_BR.jl) into one function, if the _only_ difference is spelling?  It would make sense that way&mdash;would you agree?  If you need help implementing this, please let me know.

**Comment by Gabrielforest** [comment]
@jakewilliami I have made this implementation. Indeed much better now!

**Comment by jakewilliami** [comment]
Great work Gabriel!  Sorry it has taken me a while to get back to you.  It's looking good.  One more thing: the tests seem to be failing now.  Can you take a look?  I can debug if you are too busy.

**Comment by jakewilliami** [comment]
Great work Gabriel!  Looks great :)  I'll merge now.

**Pull request merged**
